### ISSUE TITLE
When Running 'All' Playlists Tier is broken.

### ISSUE THREAD

**Issue by mattmiller87** [mattmiller87/RLScrape#12]
Per Namdorin  and confirmed by me:
```
C:\Users\matth\Documents\Github\RLScrape>python asynccsv.py -i "RSC Tracker Links - Link List.csv" -p All
retrieve:  36%|████████████████████████▌                                           | 1474/4082 [05:20<08:07,  5.35it/s]Traceback (most recent call last):
  File "asynccsv.py", line 191, in <module>
    loop.run_until_complete(singleRun())
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "asynccsv.py", line 171, in singleRun
    responses.append(await task)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 533, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "asynccsv.py", line 153, in _safe_download
    return await self.aRetrieveData(gamertag,platform)
  File "asynccsv.py", line 76, in aRetrieveData
    newrow = self._dictToList(data)
  File "asynccsv.py", line 125, in _dictToList
    newdict[season]['1T'] = pdata['Tier']
KeyError: 'Tier'
retrieve:  36%|████████████████████████▌                                           | 1474/4082 [05:50<10:20,  4.20it/s]
```

**Comment by mattmiller87** [comment]
Resolved in https://github.com/mattmiller87/RLScrape/pull/14
